### ISSUE TITLE
项目在哪呢

### ISSUE THREAD

**Issue by yjpizxq** [yuexdang/DandJourney#1]
项目在哪呢 已star

**Comment by yuexdang** [comment]
正在测试，会在这几天发布出来，目前可以暂时使用V1.0

**Comment by yuexdang** [comment]
> 项目在哪呢 已star

V1.0 https://github.com/yuexdang/MidJourney-Wrapper,
V2.0发出来我会在这个话题更新状态再关闭话题

**Comment by allentofight** [comment]
+1,项目几时出呢，期待!

**Comment by Llugaes** [comment]
绝赞催更o(TヘTo)

**Comment by zhushen12580** [comment]
> 绝赞催更o(TヘTo)
+1

**Comment by yuexdang** [comment]
感谢大家对这个项目的期待
最近在忙于毕业设计，没怎么管理过这个项目
目前V2.0先前版已发布，部分功能会在后面扩充完整
再次感谢各位的信任

**Comment by zhushen12580** [comment]
大佬，方便更新下使用教程吗 /期待

**Comment by yuexdang** [comment]
> 大佬，方便更新下使用教程吗 /期待

给我 1H，赶一个出来
