### ISSUE TITLE
关于附带image生成图片的小bug，以及解决

### ISSUE THREAD

**Issue by xxvcxxvc** [yuexdang/DandJourney#11]
![image](https://github.com/yuexdang/DandJourney/assets/44023428/1c961b2b-f2a8-4c88-9f3c-e052bd3b3c3a)
测试偶尔会出现bug，导致midjourney bot没有反应，猜测是url链接和prompt部分词汇粘连，导致识别问题
调换一下prompt和url的顺序就好了，将url放到prompt最前端

**Comment by yuexdang** [comment]
> ![image](https://user-images.githubusercontent.com/44023428/239425589-1c961b2b-f2a8-4c88-9f3c-e052bd3b3c3a.png) 测试偶尔会出现bug，导致midjourney bot没有反应，猜测是url链接和prompt部分词汇粘连，导致识别问题

关键词和链接之间有空格，理论上基本不会有这种情况，用了很长时间基本没怎么复现过这个问题
会不会是prompt里面存在某些黑名单的词汇呢

**Comment by xxvcxxvc** [comment]
> > ![image](https://user-images.githubusercontent.com/44023428/239425589-1c961b2b-f2a8-4c88-9f3c-e052bd3b3c3a.png) 测试偶尔会出现bug，导致midjourney bot没有反应，猜测是url链接和prompt部分词汇粘连，导致识别问题
> 
> 关键词和链接之间有空格，理论上基本不会有这种情况，用了很长时间基本没怎么复现过这个问题 会不会是prompt里面存在某些黑名单的词汇呢

这个确认过没有违禁词，而且midjourney报错非常诡异
![image](https://github.com/yuexdang/DandJourney/assets/44023428/0c37d98a-916a-4fcc-aafb-c03fb28296af)

**Comment by xxvcxxvc** [comment]
我知道问题了，是在prompt中添加了--style关键词导致的

**Comment by yuexdang** [comment]
> 我知道问题了，是在prompt中添加了--style关键词导致的

明白了，是不是自己调整了插入词汇的顺序，prompt词汇构建要满足：词汇 + 参数设置
可以改判断形式，但是不能调整PromptMix各个词汇的插入顺序

**Comment by xxvcxxvc** [comment]
> > 我知道问题了，是在prompt中添加了--style关键词导致的
> 
> 明白了，是不是自己调整了插入词汇的顺序，prompt词汇构建要满足：词汇 + 参数设置 可以改判断形式，但是不能调整PromptMix各个词汇的插入顺序

对，使用的时候再prompt栏手动输入了--style expressive，然后image插入了url，最后又插入了--niji5的命令，导致顺序混乱

**Comment by yuexdang** [comment]
> > > 我知道问题了，是在prompt中添加了--style关键词导致的
> > 
> > 
> > 明白了，是不是自己调整了插入词汇的顺序，prompt词汇构建要满足：词汇 + 参数设置 可以改判断形式，但是不能调整PromptMix各个词汇的插入顺序
> 
> 对，使用的时候再prompt栏手动输入了--style expressive，然后image插入了url，最后又插入了--niji5的命令，导致顺序混乱

这个下次更新会给加上一些筛选判断之类的，保证正常输入不会受到影响，以及漫画化风格的设置

**Comment by xxvcxxvc** [comment]
> > > > 我知道问题了，是在prompt中添加了--style关键词导致的
> > > 
> > > 
> > > 明白了，是不是自己调整了插入词汇的顺序，prompt词汇构建要满足：词汇 + 参数设置 可以改判断形式，但是不能调整PromptMix各个词汇的插入顺序
> > 
> > 
> > 对，使用的时候再prompt栏手动输入了--style expressive，然后image插入了url，最后又插入了--niji5的命令，导致顺序混乱
> 
> 这个下次更新会给加上一些筛选判断之类的，保证正常输入不会受到影响，以及漫画化风格的设置

好哦ヾ(◍°∇°◍)ﾉﾞ

**Comment by yuexdang** [comment]
已修复
现在对用户发送的prompt做了分割，只要不是故意搞心态，就不会出问题
经测试，这种prompt都不会出问题
输入：http://url.png prompt1 http://png.jpg prompt2 --opt 1 https://github.com prompt3 --opt 2 --opt 3
输出：http://url.png http://png.jpg prompt1 prompt2 --opt 1 --opt 2 
具体详见文档 App.apis.DiscordReply.exts.PPMethod.py

**Comment by yuexdang** [comment]
> > > > > 我知道问题了，是在prompt中添加了--style关键词导致的
> > > > 
> > > > 
> > > > 明白了，是不是自己调整了插入词汇的顺序，prompt词汇构建要满足：词汇 + 参数设置 可以改判断形式，但是不能调整PromptMix各个词汇的插入顺序
> > > 
> > > 
> > > 对，使用的时候再prompt栏手动输入了--style expressive，然后image插入了url，最后又插入了--niji5的命令，导致顺序混乱
> > 
> > 
> > 这个下次更新会给加上一些筛选判断之类的，保证正常输入不会受到影响，以及漫画化风格的设置
> 
> 好哦ヾ(◍°∇°◍)ﾉﾞ

已修复
现在对用户发送的prompt做了分割，只要不是故意搞心态，就不会出问题
经测试，这种prompt都不会出问题
输入：http://url.png/ prompt1 http://png.jpg/ prompt2 --opt 1 https://github.com/ prompt3 --opt 2 --opt 3
输出：http://url.png/ http://png.jpg/ prompt1 prompt2 --opt 1 --opt 2
具体详见文档 App.apis.DiscordReply.exts.PPMethod.py
