### ISSUE TITLE
频道用户如何使用图片细分功能

### ISSUE THREAD

**Issue by dnvljty** [yuexdang/DandJourney#17]
请问通过/dj 生成图片后，对图片进行UV操作是怎样实现的？

**Comment by yuexdang** [comment]
emmmmm不是直接点按钮就可以了嘛
或者可以发一张图看看嘛

**Comment by yuexdang** [comment]
比如这张图直接点下面的按钮就行
> ![image](https://github.com/yuexdang/DandJourney/assets/56034408/c2a29577-b8e6-419c-9931-9ad6500297cf)

**Comment by dnvljty** [comment]
感谢，使用浏览器访问频道貌似没有这个界面。
![111](https://github.com/yuexdang/DandJourney/assets/17612655/8cd2e301-0063-4db4-a5c5-78b628ccb17f)

**Comment by yuexdang** [comment]
> 感谢，使用浏览器访问频道貌似没有这个界面。 ![111](https://user-images.githubusercontent.com/17612655/241613147-8cd2e301-0063-4db4-a5c5-78b628ccb17f.png)

为什么MidJourney的消息被删除了，我有些不明白
MidJourney的消息不能被删除，否则无法正常进行细分操作
要是不删除还有这个问题一般就是机器人名字错了

**Comment by dnvljty** [comment]
感谢，问题已解决，设置机器人名字时加了#号及数字。
