### ISSUE TITLE
请问消息中的#未知标签是什么？

### ISSUE THREAD

**Issue by hmilyfyj** [yuexdang/DandJourney#18]
如图，感谢解答。

<img width="428" alt="image" src="https://github.com/yuexdang/DandJourney/assets/10796377/71e89105-7ed5-4c2b-bc58-48ed8a0bf3d6">

**Comment by yuexdang** [comment]
未知标签是一串数字，用于标识这个消息的发送者等信息，从而将用户和消息进行绑定

这个是后面将其抽离出discord平台的基础

![image](https://github.com/yuexdang/DandJourney/assets/56034408/5022a8a2-2f55-4791-ba15-9d4d364601f8)

输出的内容其实是<#TimeStamp + DQueueID> 用于在队列中找到DQueueID对应的用户信息
