### ISSUE TITLE
我使用 MidJourney-Wrapper对接了微信机器人，希望能够加入项目

### ISSUE THREAD

**Issue by liustar1989** [yuexdang/DandJourney#2]
我使用 MidJourney-Wrapper对接了微信机器人，实现了一对一的生成图片及回复，U和V操作，还有历史消息的操作，希望能够加入项目，请问怎么联系？

**Comment by yuexdang** [comment]
> 我使用 MidJourney-Wrapper对接了微信机器人，实现了一对一的生成图片及回复，U和V操作，还有历史消息的操作，希望能够加入项目，请问怎么联系？

团队纯属用爱发电没有限制，您想加入我们团队我感觉十分荣幸。如果可以的话，我想简单了解一下您的使用原理，或者授权一个私有库的权限，这样我能更好了解您的逻辑思路，以便我在数据传递的时候能满足您的需求。

**Comment by liustar1989** [comment]
> > 我使用 MidJourney-Wrapper对接了微信机器人，实现了一对一的生成图片及回复，U和V操作，还有历史消息的操作，希望能够加入项目，请问怎么联系？
> 
> 团队纯属用爱发电没有限制，您想加入我们团队我感觉十分荣幸。如果可以的话，我想简单了解一下您的使用原理，或者授权一个私有库的权限，这样我能更好了解您的逻辑思路，以便我在数据传递的时候能满足您的需求。

我目前的代码没有模块化，也挺乱的，所以没有上传，是否可以加个wx我发你？liustar1989
