### ISSUE TITLE
请问其他用户能否添加我建立的机器人到自建的服务器使用？

### ISSUE THREAD

**Issue by sunnysnake** [yuexdang/DandJourney#20]
其实就是如何达到他们作图各自不受干扰

**Comment by yuexdang** [comment]
这个机器人目前只支持一个付费账号的绑定，如果你的需求是多个账号，那么目前并不支持
理论上只需要为机器人在不同的频道配置不同的账号关联信息即可，这个得看想要怎么配置，比如是自助填写字段之类的，其实就是需要添加一个关联关系即可，让vip_token与serverID进行绑定
但是不建议这么做，这样做严重违反了MidJourney的用户要求，如果造成MidJourney方面的封禁将无法单方面解除
如果需求指向的其他目标，请举例详细说明

**Comment by sunnysnake** [comment]
已建立私有频道解决需求
