### ISSUE TITLE
应用程序未响应

### ISSUE THREAD

**Issue by jokeredmund** [yuexdang/DandJourney#22]
提示应用程序未响应，已经更新代码重新部署仍然不行，然后觉得是不是VIP TOKEN这些需要重新设置，但是发现现在网页端抓不到authorization: VIP_TOKEN(String)这个了，请问是哪个模块出了问题？

**Comment by yuexdang** [comment]
我这边无法复现你的问题，包括authorization依然可以获得（https://discord.com/api/v9/interactions的请求中）
如果可以的话请提交一份代码或者上传到你的仓库中，我会clone下来看一下问题出在哪儿

或者请补充以下细节：
1.是所有命令（/dhelp等都无法使用）还是只有单个命令（单个命令则有哪些无法使用）
2.自己修改的内容除了环境的配置数据还有哪些
3.启动环境（Python==3.10+）与必须库的检查

**Comment by jokeredmund** [comment]
Unauthorized是为什么呀，我discord里可以用的

**Comment by jokeredmund** [comment]
INTERACTION_APPLICATION_COMMAND_INVALID_VERSION

**Comment by yuexdang** [comment]
没明白，感觉咱们两个各说各的

要不截个图也行

**Comment by jokeredmund** [comment]
现在是提示ResponseError in Location:ResponseCheck, Msg:{"code": 50035, "errors": {"channel_id": {"_errors": [{"code": "NUMBER_TYPE_COERCE", "message": "\"False\"\u503c\u4e0d\u662fsnowflake\u3002"}]}}, "message": "Invalid Form Body"}, Code:400

**Comment by yuexdang** [comment]
稍等，我电脑坏了，请确认你的Midjourney账号还能使用Midjourney的指令，以确保你的账号没有过期
我感觉像是账号过期了

**Comment by jokeredmund** [comment]
mj账号还可以画画的

**Comment by jokeredmund** [comment]
不好意思，找到原因了，是我自己的问题。agent channel配置错了，现在可以了。谢谢
