### ISSUE TITLE
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [信号灯超时时间已到]

### ISSUE THREAD

**Issue by zhushen12580** [yuexdang/DandJourney#5]
代理解决方法有哪些呢

**Comment by yuexdang** [comment]
proxy 一直是一个问题，追溯到最之前的 MidJourney_Warpper 都有这个问题（proxy这一参数在discord.py的进化中不断的被启用与弃用）

后面在处理微信接入的时候会考虑代理的问题，现在的临时解决方案是部署在国外的托管平台上或者没有墙的服务器上（HongKang ect），这样就不需要代理了

**Comment by yuexdang** [comment]
我试了转发请求去解决这个问题，覆写了一些关于http和discord的组件，但是效果不怎么样.
过段时间吧 i.py会直接提供这个东西的支持
到时候就好搞了

**Comment by yuexdang** [comment]
> 代理解决方法有哪些呢

proxy代理已支持
添加proxy_url即可
具体详见usage.md
