### ISSUE TITLE
关于代理相关

### ISSUE THREAD

**Issue by xxvcxxvc** [yuexdang/DandJourney#6]
您好大佬，请问Interactions怎样才能像在Discordjs一样使用代理？
例如：
discord.Bot(intents=discord.Intents.all(), proxy='http://127.0.0.1:7890')

**Comment by yuexdang** [comment]
目前还不支持，i.py v5还在更新中
除了用aiohttp兜圈子的方法解决这个问题以外，目前最好的方法就是把它部署在国外的服务器上（比如Railway）
当然如果有人发现了更好的方法去解决这个问题欢迎在下面补充

**Comment by xxvcxxvc** [comment]
> 目前还不支持，i.py v5还在更新中 除了用aiohttp兜圈子的方法解决这个问题以外，目前最好的方法就是把它部署在国外的服务器上（比如Railway） 当然如果有人发现了更好的方法去解决这个问题欢迎在下面补充

**Comment by xxvcxxvc** [comment]
多谢大佬回答

**Comment by yuexdang** [comment]
i.py更新了，后面会加上proxy参数用于代理
先稍等我把毕设整完

**Comment by yuexdang** [comment]
> 您好大佬，请问Interactions怎样才能像在Discordjs一样使用代理？ 例如： discord.Bot(intents=discord.Intents.all(), proxy='http://127.0.0.1:7890')

proxy代理已支持
添加proxy_url即可
具体详见usage.md
