### ISSUE TITLE
求问CHANNEL_SIGN相关参数

### ISSUE THREAD

**Issue by xxvcxxvc** [yuexdang/DandJourney#9]
请问如果我想使用USE_MESSAGED_CHANNEL，在CHANNEL_SIGN应该填入什么信息呀？

**Comment by yuexdang** [comment]
CHANNEL_SIGN ： 是否需要适应不同频道(默认为False)
详情可参考https://github.com/yuexdang/DandJourney/blob/main/Doc/Usage.md#%E6%9C%BA%E5%99%A8%E4%BA%BA%E9%83%A8%E7%BD%B2

**Comment by yuexdang** [comment]
如果需要使用，改为True即可
这个是用来控制是否需要MidJourney根据用户调用的频道来调整回复的位置的

**Comment by xxvcxxvc** [comment]
好嘞，感谢~
